name: auto deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Use node ver10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install and build
        run: |
          yarn
          yarn run build

      - name: Deploy
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.USTC_MIRROR }}
          ARGS: "-avz --delete"
          SERVER_PORT: "22"
          FOLDER: ./
          SERVER_IP: ${{ secrets.USTC_MIRROR_HOST }}
          USERNAME: ${{ secrets.USTC_MIRRO_USER }}
          SERVER_DESTINATION: /home/zeka/files/ustc-next

